### ISSUE TITLE
Issues Installing conda environment.

### ISSUE THREAD

**Issue by vivek2000anand** [wichmann-lab/scaling-dimension#1]
![scaling_dimension_error](https://github.com/wichmann-lab/scaling-dimension/assets/37226693/1f2e5bc0-8b39-4b70-bbaf-0a685f3dc0ac)

I tried installing the conda environment to try out the experiments given in the repo. After looking at the cblearn pypi repo, this seems like it may be an issue with the python version as cblearn only seems to support python 3.9 onwards while the yaml includes python=3.8.8.

If that is the case, could you please update the yaml file? If not, what seems to be the issue?

**Comment by dekuenstle** [comment]
I updated the setup instructions; I hope it works now for you. 
This repo intentionally uses an old version of *cblearn*, i.e., from when this repo was created, to archive the experiments from the paper.

If you are interested in using the method, I recommend the implementation in the latest version of *cblearn*:
[cblearn.embedding.estimate_dimensionality_cv](https://cblearn.readthedocs.io/en/revision/references/generated/cblearn.embedding.estimate_dimensionality_cv.html#cblearn.embedding.estimate_dimensionality_cv)

In case of further problems, you can also [email me](mailto:david-elias.kuenstle@uni-tuebingen.de).
